name: wrapped_korean_text
description: Text widget that wraps Korean string without word-breaks. Well spaced Hangeul as it should be.
version: 0.0.2
homepage: https://github.com/studio-b-co-kr/wrapped_korean_text

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
